Add Dwell Time definition to Stations
socialedge/hermes pull request #154
Opened 2017-06-25 18:29 UTC by wingsofovnia

Resolves #151

2017-06-25 19:20 UTC, glasierr requested changes

2017-06-25 19:20 UTC, glasierr commented on backend/backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/Dwell.java
> +    public static void main(String[] a) {
May be removed

2017-06-25 20:34 UTC, wingsofovnia commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/BasicScheduleGenerator.java
> +        stops.add(new Stop(startTime, startTime, headStation));
I removed `startTime.plus..` as a departure for the first station since it's strange to make a stop at the very first station. Am I right?

2017-06-26 04:23 UTC, glasierr commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/BasicScheduleGenerator.java
> +        val headStation = route.iterator().next().getBegin();
It is called tail station, isn't it? You also could use route.getTail() method for simplicity

2017-06-26 04:28 UTC, glasierr commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/UniformDwellTimeResolver.java
> +        val dwellTime = calculateDwellTimeUniformly(applicableDwell.getDwellTime(), applicableDwell.getProbability());
Optional handling and this method invocation can be replaced with simple Optional.map()

2017-06-26 04:29 UTC, glasierr commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/UniformDwellTimeResolver.java
> +    public static void main(String[] a) {
:)

2017-06-26 04:29 UTC, glasierr requested changes
I've left some comments

2017-06-26 05:24 UTC, wingsofovnia commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/BasicScheduleGenerator.java
> +        val headStation = route.iterator().next().getBegin();
It's not a tail station, but a head station. 
`route.iterator().next()``.getBegin();`
....... first segment..........first station...

2017-06-26 05:25 UTC, glasierr commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/BasicScheduleGenerator.java
> +        val headStation = route.iterator().next().getBegin();
So look at the Route#getTail method, I think it returns first and getHead returns last station

2017-06-26 05:27 UTC, wingsofovnia commented on backend/backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/gen/basic/UniformDwellTimeResolver.java
> +    public static void main(String[] a) {
D'OH
again

2017-06-26 05:38 UTC, glasierr approved these changes
Good job, man

2017-06-26 05:40 UTC, merged