Create google maps api based shape factory
socialedge/hermes pull request #79
Opened 2017-03-18 17:04 UTC by glasierr

2017-03-18 17:45 UTC, wingsofovnia requested changes

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +        val shapePoints = new ArrayList<ShapePoint>();
new ArrayList<ShapePoint>(resultElements.length)

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/TransitRuntimeException.java
> +package eu.socialedge.hermes.backend.core;
Header missed

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/test/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactoryTest.java
> +package eu.socialedge.hermes.backend.core;
header

2017-03-18 17:45 UTC, wingsofovnia commented on dependencies.gradle
>              unitsMeasurement: "tec.uom:uom-se:${versions.geo.unitsMeasurement}"
it's not geo, but commons

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +            .map(GoogleMapsShapeFactory::toLatLng)
skip(1) missed?

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +    private DistanceMatrix calculateDistanceMatrix(List<Location> points) {
Consider this signature `Map<Location, Quantity> calculateDistanceTraveled(Location origin, List<Location> waypoints)`

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +            throw new TransitRuntimeException("Exception occurred during distance matrix calculation", e);
It's not a TransitRuntimeException, but Http exception or IOException

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +                throw new TransitRuntimeException("Couldn't recognize location " + pointLocation);
Imho all this factory has nothing to do with "transit". com.google.maps.errors.NotFoundException or generic "ShapeFactoryException" are a good candidates.

2017-03-18 17:45 UTC, wingsofovnia commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +            val quantity = Quantities.getQuantity(element.distance.inMeters, Units.METRE);
What was the case for previous pull request if you still give no choice for programmer who uses this factory? Consider adding Units to ShapeFactory#create:
```
Shape create(List<Location> points, Units units);
default Shape create(List<Location> points) {
   return create(points, Units.METRE);
}
```

2017-03-18 17:47 UTC, glasierr commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +            val quantity = Quantities.getQuantity(element.distance.inMeters, Units.METRE);
The reason to add Quantity - to make it clear what unit of lenght is used and to make it easy for consumers to make conversions

2017-03-18 17:49 UTC, glasierr commented on backend-core/src/main/java/eu/socialedge/hermes/backend/core/GoogleMapsShapeFactory.java
> +            .map(GoogleMapsShapeFactory::toLatLng)
No, we definetely need to have distance first - first point (will always be 0), according to gtfs specification

2017-03-18 17:50 UTC, glasierr commented on dependencies.gradle
>              unitsMeasurement: "tec.uom:uom-se:${versions.geo.unitsMeasurement}"
Wasn't it approved by you in previous pull request?

2017-03-20 12:41 UTC, wingsofovnia approved these changes

2017-03-20 12:42 UTC, merged