Implement basic schedule generator
socialedge/hermes pull request #91
Opened 2017-04-07 16:59 UTC by glasierr

resolves #80

2017-04-08 06:12 UTC, wingsofovnia requested changes

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +    private @NonNull String description;
What is `@NonNull` for here?

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +        timePoints.sort(Comparator.comparing(TimePoint::time));
Consider passing comparator to `generateTimePoints` method

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +            trips.addAll(generateVehicleTrips(vehId, startPoint, timePoints));
imho it's not good to modify startPoint inside `generateVehicleTrips`

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +        val speedValue = averageSpeed.to(Units.METRE_PER_SECOND).getValue().longValue();
speedValue -> averageSpeedVal :) ?

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +            val distTravelled = route.shape().shapePoints().stream()
Consider extracting to another method like `Optional<Quantity<Length>> distanceTraveled(Route r)`

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +    private static TimePoint getNextNotServicedTimePoint(List<TimePoint> timePoints) {
findNextNotServicedTimePoint

2017-04-08 06:12 UTC, wingsofovnia commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/Schedule.java
>      public Collection<Trip> trips() {
Make it List<Trip> to be consistent with other classes eg https://github.com/socialedge/hermes/blob/develop-v2/backend-transit/src/main/java/eu/socialedge/hermes/backend/transit/domain/Route.java#L104

2017-04-08 11:44 UTC, glasierr commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +    private @NonNull String description;
It is required for Schedule

2017-04-08 11:44 UTC, glasierr commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +        timePoints.sort(Comparator.comparing(TimePoint::time));
I'll just move this sorting to that methot

2017-04-08 11:54 UTC, glasierr commented on backend-schedule/src/main/java/eu/socialedge/hermes/backend/schedule/domain/BasicScheduleGenerator.java
> +    private static TimePoint getNextNotServicedTimePoint(List<TimePoint> timePoints) {
I understand "find" like looking for something that might not exist. But this method assumes that next not services time point exists, so just "gets" it

2017-04-09 17:41 UTC, wingsofovnia approved these changes

2017-04-09 17:43 UTC, merged